CREATE TABLE city
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default",
    "departmentId" bigint,
    CONSTRAINT city_pkey PRIMARY KEY (id),
    CONSTRAINT city_department FOREIGN KEY ("departmentId")
        REFERENCES department (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

INSERT INTO city(name, "departmentId") VALUES (UPPER('El Encanto'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Chorrera'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Pedrera'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Victoria'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Leticia'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Miriti - Paraná'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Alegria'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Arica'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Nariño'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Santander'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tarapacá'),1);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cáceres'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caucasia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Bagre'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nechí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tarazá'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zaragoza'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caracolí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Maceo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Berrio'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Nare'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Triunfo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yondó'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Amalfi'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Anorí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cisneros'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Remedios'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Roque'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santo Domingo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Segovia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vegachí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yalí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yolombó'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Angostura'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belmira'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Briceño'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Campamento'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carolina'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Don Matias'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Entrerrios'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gómez Plata'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guadalupe'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ituango'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Andrés'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San José De La Montaña'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pedro'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Rosa De Osos'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Toledo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valdivia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yarumal'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Abriaquí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Anza'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Armenia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buriticá'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cañasgordas'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Dabeiba'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ebéjico'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Frontino'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Giraldo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Heliconia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Liborina'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Olaya'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Peque'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabanalarga'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Jerónimo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santafé De Antioquia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sopetran'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Uramita'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Abejorral'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Alejandría'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Argelia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carmen De Viboral'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cocorná'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Concepción'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Granada'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guarne'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guatape'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Ceja'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Unión'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Marinilla'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nariño'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Peñol'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Retiro'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rionegro'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Carlos'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Francisco'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Luis'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Rafael'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Vicente'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santuario'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sonson'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Amaga'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Andes'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Angelopolis'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Betania'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Betulia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caicedo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caramanta'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ciudad Bolívar'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Concordia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fredonia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hispania'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jardín'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jericó'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Pintada'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Montebello'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pueblorrico'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Salgar'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Barbara'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Támesis'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tarso'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Titiribí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Urrao'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valparaiso'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Venecia'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Apartadó'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arboletes'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carepa'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chigorodó'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Murindó'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mutata'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Necoclí'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juan De Uraba'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pedro De Uraba'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Turbo'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vigía Del Fuerte'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barbosa'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bello'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caldas'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Copacabana'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Envigado'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Girardota'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Itagui'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Estrella'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Medellín'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabaneta'),2);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arauca'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arauquita'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cravo Norte'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fortul'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Rondón'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Saravena'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tame'),3);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Providencia Y Santa Catalina'),4);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Andres'),4);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barranquilla'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Galapa'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Malambo'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Colombia'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Soledad'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Campo De La Cruz'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Candelaria'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Luruaco'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Manati'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Repelon'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Lucia'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Suan'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Baranoa'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palmar De Varela'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Polonuevo'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ponedera'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabanagrande'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabanalarga'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santo Tomas'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Juan De Acosta'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Piojó'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tubara'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Usiacuri'),5);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bogota D.C.'),6);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cicuco'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hatillo De Loba'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Margarita'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mompós'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Fernando'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Talaigua Nuevo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arjona'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arroyohondo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Calamar'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cartagena'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Clemencia'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mahates'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Cristobal'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Estanislao'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Catalina'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Rosa De Lima'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Soplaviento'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Turbaco'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Turbana'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villanueva'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Altos Del Rosario'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barranco De Loba'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Peñon'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Regidor'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Río Viejo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Martin De Loba'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arenal'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cantagallo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Morales'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pablo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Rosa Del Sur'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Simití'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Achí'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Magangué'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Montecristo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pinillos'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Jacinto Del Cauca'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tiquisio'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carmen De Bolívar'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Córdoba'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Guamo'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('María La Baja'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Jacinto'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juan Nepomuceno'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zambrano'),7);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chíquiza'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chivatá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cómbita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cucaita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Motavita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Oicatá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Samacá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Siachoque'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sora'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Soracá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sotaquirá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Toca'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tunja'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tuta'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ventaquemada'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chiscas'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cubará'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Cocuy'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Espino'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guacamayas'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Güicán'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Panqueba'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Labranzagrande'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pajarito'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paya'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pisba'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Berbeo'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Campohermoso'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Miraflores'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Páez'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Eduardo'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zetaquira'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Boyacá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ciénega'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jenesano'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nuevo Colón'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ramiriquí'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rondón'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tibaná'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Turmequé'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Umbita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Viracachá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chinavita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Garagoa'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Macanal'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pachavita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Luis De Gaceno'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa María'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Boavita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Covarachía'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Uvita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Mateo'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sativanorte'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sativasur'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Soatá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Susacón'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tipacoque'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Briceño'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buenavista'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caldas'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chiquinquirá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Coper'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Victoria'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Maripí'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Muzo'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Otanche'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pauna'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Boyaca'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quípama'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Saboyá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Miguel De Sema'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pablo Borbur'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tununguá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Almeida'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chivor'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guateque'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guayatá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Capilla'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Somondoco'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sutatenza'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tenza'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arcabuco'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chitaraque'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gachantivá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Moniquirá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ráquira'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sáchica'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San José De Pare'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Sofía'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santana'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sutamarchán'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tinjacá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Togüí'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villa De Leyva'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aquitania'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cuítiva'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Firavitoba'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gameza'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Iza'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mongua'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Monguí'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nobsa'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pesca'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sogamoso'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tibasosa'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tópaga'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tota'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belén'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Busbanzá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cerinza'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Corrales'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Duitama'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Floresta'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paipa'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Rosa Viterbo'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tutazá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Betéitiva'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chita'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jericó'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paz De Río'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Socha'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Socotá'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tasco'),8);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Filadelfia'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Merced'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Marmato'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Riosucio'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Supía'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Manzanares'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Marquetalia'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Marulanda'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pensilvania'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Anserma'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belalcázar'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Risaralda'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San José'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Viterbo'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chinchina'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Manizales'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Neira'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palestina'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villamaria'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aguadas'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aranzazu'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pácora'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Salamina'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Dorada'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Norcasia'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Samaná'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Victoria'),9);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Albania'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belén De Los Andaquies'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cartagena Del Chairá'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Currillo'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Doncello'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Paujil'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Florencia'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Montañita'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Milan'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Morelia'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Rico'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Jose Del Fragua'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Vicente Del Caguán'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Solano'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Solita'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valparaiso'),10);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aguazul'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chameza'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hato Corozal'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Salina'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Maní'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Monterrey'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nunchía'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Orocué'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paz De Ariporo'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pore'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Recetor'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabanalarga'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sácama'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Luis De Palenque'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Támara'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tauramena'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Trinidad'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villanueva'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yopal'),11);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cajibío'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Tambo'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Sierra'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Morales'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Piendamo'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Popayán'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rosas'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sotara'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Timbio'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buenos Aires'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caloto'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Corinto'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Miranda'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Padilla'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Tejada'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santander De Quilichao'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Suarez'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villa Rica'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guapi'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lopez'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Timbiqui'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caldono'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Inzá'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jambalo'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paez'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Purace'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Silvia'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Toribio'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Totoro'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Almaguer'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Argelia'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Balboa'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bolívar'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Florencia'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Vega'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mercaderes'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Patia'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Piamonte'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Sebastian'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Rosa'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sucre'),12);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Becerril'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chimichagua'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chiriguana'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Curumaní'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Jagua De Ibirico'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pailitas'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tamalameque'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Astrea'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bosconia'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Copey'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Paso'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Agustín Codazzi'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Paz'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Manaure'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pueblo Bello'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Diego'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valledupar'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aguachica'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gamarra'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('González'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Gloria'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pelaya'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Río De Oro'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Alberto'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Martín'),13);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Atrato'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bagadó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bojaya'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Carmen De Atrato'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lloró'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Medio Atrato'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quibdó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rio Quito'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Acandí'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belén De Bajira'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carmén Del Darién'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Riosucio'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Unguía'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bahía Solano'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Juradó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nuquí'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Alto Baudó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bajo Baudó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Litoral Del San Juan'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Medio Baudó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Canton De San Pablo'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Certegui'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Condoto'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Itsmina'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Medio San Juan'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nóvita'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Río Frío'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San José Del Palmar'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sipí'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tadó'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Union Panamericana'),14);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tierralta'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valencia'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chimá'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cotorra'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lorica'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Momil'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Purísima'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Montería'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Canalete'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Los Córdobas'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Moñitos'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Escondido'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Antero'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Bernardo Del Viento'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chinú'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sahagún'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Andrés Sotavento'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ayapel'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buenavista'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Apartada'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Montelíbano'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Planeta Rica'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pueblo Nuevo'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Libertador'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cereté'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ciénaga De Oro'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Carlos'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pelayo'),15);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chocontá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Macheta'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Manta'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sesquilé'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Suesca'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tibirita'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villapinzón'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Agua De Dios'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Girardot'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guataquí'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jerusalén'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nariño'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nilo'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ricaurte'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tocaima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caparrapí'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guaduas'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Salgar'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Albán'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Peña'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Vega'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nimaima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nocaima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quebradanegra'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Francisco'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sasaima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Supatá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Útica'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vergara'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villeta'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gachala'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gacheta'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gama'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guasca'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guatavita'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Junín'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Calera'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ubalá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Beltrán'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bituima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chaguaní'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guayabal De Siquima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puli'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juan De Río Seco'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vianí'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Medina'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paratebueno'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caqueza'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chipaque'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Choachí'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fomeque'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fosca'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guayabetal'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gutiérrez'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quetame'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ubaque'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Une'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Peñón'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Palma'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pacho'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paime'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Cayetano'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Topaipi'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villagomez'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yacopí'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cajicá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chía'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cogua'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gachancipá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nemocon'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sopó'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tabio'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tocancipá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zipaquirá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bojacá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cota'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Rosal'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Facatativá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Funza'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Madrid'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mosquera'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Subachoque'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tenjo'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zipacon'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sibaté'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Soacha'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arbeláez'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cabrera'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fusagasugá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Granada'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pandi'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pasca'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Bernardo'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Silvania'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tibacuy'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Venecia'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Anapoima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Anolaima'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Apulo'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cachipay'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Colegio'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Mesa'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quipile'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Antonio De Tequendama'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tena'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Viotá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carmen De Carupa'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cucunubá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fúquene'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guachetá'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lenguazaque'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Simijaca'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Susa'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sutatausa'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tausa'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ubate'),16);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barranco Mina'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cacahual'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Inírida'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Guadalupe'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mapiripan'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Morichal'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pana Pana'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Colombia'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Felipe'),17);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Calamar'),18);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Retorno'),18);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Miraflores'),18);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San José Del Guaviare'),18);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Agrado'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Altamira'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Garzón'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gigante'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guadalupe'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pital'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Suaza'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tarqui'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aipe'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Algeciras'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Baraya'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Campoalegre'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Colombia'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hobo'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Iquira'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Neiva'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palermo'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rivera'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa María'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tello'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Teruel'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villavieja'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yaguará'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Argentina'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Plata'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nátaga'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Paicol'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tesalia'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Acevedo'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Elías'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Isnos'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Oporapa'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palestina'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pitalito'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Saladoblanco'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Agustín'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Timaná'),19);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Albania'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Dibulla'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Maicao'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Manaure'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Riohacha'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Uribia'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barrancas'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Distraccion'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Molino'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fonseca'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hatonuevo'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Jagua Del Pilar'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juan Del Cesar'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Urumita'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villanueva'),20);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ariguaní'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chibolo'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nueva Granada'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Plato'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabanas De San Angel'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tenerife'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Algarrobo'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aracataca'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ciénaga'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Reten'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fundacion'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pueblo Viejo'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zona Bananera'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cerro San Antonio'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Concordia'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Piñon'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pedraza'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pivijay'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Remolino'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Salamina'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sitionuevo'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zapayan'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Marta'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Banco'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guamal'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pijiño Del Carmen'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Sebastian De Buenavista'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Zenon'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Ana'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Barbara De Pinto'),21);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Castillo'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Dorado'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fuente De Oro'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Granada'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Macarena'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Uribe'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lejanías'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mapiripan'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mesetas'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Concordia'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Lleras'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Rico'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juan De Arama'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vista Hermosa'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villavicencio'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Acacias'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barranca De Upia'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Castilla La Nueva'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cumaral'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Calvario'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guamal'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Restrepo'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Carlos Guaroa'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juanito'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Luis De Cubarral'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Martín'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cabuyaro'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Gaitán'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Lopez'),22);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chachagui'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Consaca'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Peñol'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Tambo'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Florida'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Nariño'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pasto'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sandoná'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tangua'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yacuanquer'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ancuya'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guaitarilla'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Llanada'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Linares'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Los Andes'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mallama'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ospina'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Providencia'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ricaurte'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Samaniego'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Cruz'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sapuyes'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tuquerres'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barbacoas'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Charco'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Francisco Pizarro'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Tola'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Magui'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mosquera'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Olaya Herrera'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Roberto Payan'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Barbara'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tumaco'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Alban'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arboleda'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belen'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buesaco'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Colon'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cumbitara'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Rosario'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Tablon De Gomez'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Cruz'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Union'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Leiva'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Policarpa'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Bernardo'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Lorenzo'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pablo'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pedro De Cartago'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Taminango'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aldana'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Contadero'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Córdoba'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cuaspud'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cumbal'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Funes'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guachucal'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gualmatan'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Iles'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Imues'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ipiales'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Potosí'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerres'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pupiales'),23);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Arboledas'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cucutilla'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gramalote'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lourdes'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Salazar'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santiago'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villa Caro'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bucarasica'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Tarra'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sardinata'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tibú'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Abrego'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cachirá'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Convención'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Carmen'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hacarí'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Esperanza'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Playa'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ocaña'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Calixto'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Teorama'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cúcuta'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Zulia'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Los Patios'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Santander'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Cayetano'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villa Del Rosario'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cácota'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chitagá'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mutiscua'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pamplona'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pamplonita'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Silos'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bochalema'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chinácota'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Durania'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Herrán'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Labateca'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ragonvalia'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Toledo'),24);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Colón'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mocoa'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Orito'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Asis'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Caicedo'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Guzman'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Leguizamo'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Francisco'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Miguel'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santiago'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sibundoy'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valle Del Guamuez'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villa Garzon'),25);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Armenia'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buenavista'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Calarca'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cordoba'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Genova'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pijao'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Filandia'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Salento'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Circasia'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Tebaida'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Montengro'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quimbaya'),26);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Dosquebradas'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Virginia'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Marsella'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pereira'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Rosa De Cabal'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Apía'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Balboa'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Belén De Umbría'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guática'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Celia'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Quinchia'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santuario'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mistrató'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pueblo Rico'),27);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chima'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Confines'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Contratación'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Guacamayo'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Galán'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Gambita'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guadalupe'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guapotá'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Hato'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Oiba'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palmar'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palmas Del Socorro'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Helena Del Opón'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Simacota'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Socorro'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Suaita'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Capitanejo'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carcasí'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cepitá'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cerrito'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Concepción'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Enciso'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guaca'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Macaravita'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Málaga'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Molagavita'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Andrés'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San José De Miranda'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Miguel'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aratoca'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barichara'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cabrera'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Charalá'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Coromoro'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Curití'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Encino'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jordán'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mogotes'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ocamonte'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Onzaga'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Páramo'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pinchote'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Gil'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Joaquín'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valle De San José'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villanueva'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barrancabermeja'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Betulia'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Carmen De Chucurí'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Wilches'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sabana De Torres'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Vicente De Chucurí'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zapatoca'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bucaramanga'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('California'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Charta'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Playón'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Floridablanca'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Girón'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lebríja'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Los Santos'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Matanza'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Piedecuesta'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rionegro'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Bárbara'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Surata'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tona'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vetas'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Aguada'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Albania'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Barbosa'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bolívar'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chipatá'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cimitarra'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Peñón'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Florián'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guavatá'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guepsa'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jesús María'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Belleza'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Paz'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Landázuri'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puente Nacional'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Parra'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Benito'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sucre'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vélez'),28);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guaranda'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Majagual'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sucre'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chalán'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Coloso'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Morroa'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ovejas'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sincelejo'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Coveñas'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palmito'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Onofre'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santiago De Tolú'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tolú Viejo'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buenavista'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Corozal'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Roble'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Galeras'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Los Palmitos'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sampués'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Juan Betulia'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pedro'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sincé'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caimito'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Unión'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Benito Abad'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Marcos'),29);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ambalema'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Armero'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Falan'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Fresno'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Honda'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mariquita'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palocabildo'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Carmen De Apicalá'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cunday'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Icononzo'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Melgar'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villarrica'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ataco'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Chaparral'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Coyaima'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Natagaima'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ortega'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Planadas'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rioblanco'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Roncesvalles'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Antonio'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Alvarado'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Anzoátegui'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cajamarca'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Coello'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Espinal'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Flandes'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ibague'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Piedras'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Rovira'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Luis'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Valle De San Juan'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Alpujarra'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Dolores'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guamo'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Prado'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Purificación'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Saldaña'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Suárez'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Casabianca'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Herveo'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Lerida'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Libano'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Murillo'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Isabel'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Venadillo'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Villahermosa'),30);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Andalucía'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buga'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bugalagrande'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Calima'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Cerrito'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ginebra'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Guacarí'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Restrepo'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Riofrio'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('San Pedro'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Trujillo'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Tuluá'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yotoco'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Alcala'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ansermanuevo'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Argelia'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Bolívar'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cartago'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Águila'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Cairo'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('El Dovio'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Unión'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Victoria'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Obando'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Roldanillo'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Toro'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Ulloa'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Versalles'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Zarzal'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Buenaventura'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caicedonia'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Sevilla'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cali'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Candelaria'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Dagua'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Florida'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Jamundí'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Cumbre'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Palmira'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pradera'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Vijes'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yumbo'),31);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Caruru'),32);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Mitú'),32);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Pacoa'),32);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Papunahua'),32);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Taraira'),32);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Yavaraté'),32);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Cumaribo'),33);
INSERT INTO city(name, "departmentId") VALUES (UPPER('La Primavera'),33);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Puerto Carreño'),33);
INSERT INTO city(name, "departmentId") VALUES (UPPER('Santa Rosalía'),33);